former_employers:
    label: Former Employers
    view:
        list: $/newvertical/jobforms/models/formeremployer/columns.yaml
        recordsPerPage: 4
    manage:
        form: $/newvertical/jobforms/models/formeremployer/fields.yaml
references:
    label: References
    view:
        list: $/newvertical/jobforms/models/reference/columns.yaml
        recordsPerPage: 3
    manage:
        form: $/newvertical/jobforms/models/reference/fields.yaml
