plugin:
    name: 'newvertical.jobforms::lang.plugin.name'
    description: 'newvertical.jobforms::lang.plugin.description'
    author: newvertical
    icon: oc-icon-bar-chart-o
    homepage: ''
navigation:
    careers:
        label: Careers
        url: /
        icon: icon-bar-chart-o
        sideMenu:
            joblisting:
                label: 'Job Listings'
                url: newvertical/jobforms/joblistings
                icon: icon-pencil-square-o
            submissions:
                label: 'Job Submissions'
                url: newvertical/jobforms/jobapplications
                icon: icon-envelope-o
