name: JobListings
modelClass: newvertical\Jobforms\Models\JobListing
form: $/newvertical/jobforms/models/joblisting/fields.yaml
defaultRedirect: newvertical/jobforms/joblistings
create:
    redirect: 'newvertical/jobforms/joblistings/update/:id'
    redirectClose: newvertical/jobforms/joblistings
update:
    redirect: newvertical/jobforms/joblistings
    redirectClose: newvertical/jobforms/joblistings
preview: {  }
